#Render changes database URLs dynamically, so use:
#spring.datasource.url=${DATABASE_URL}
#instead of hardcoding the DB address.

spring.application.name=election-system
server.port=9091
spring.datasource.url=jdbc:postgresql://localhost:5432/election_db
spring.datasource.username=postgres
spring.datasource.password=master

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true